[package]
name = "ariel-os-hello"
version = "0.1.0"
edition = "2024"

[dependencies]
ariel-os = { path = "build/imports/ariel-os/src/ariel-os", features = ["time", "external-interrupts","spi"] }
ariel-os-boards = { path = "build/imports/ariel-os/src/ariel-os-boards" }

esp-hal = { version = "~1.0.0", default-features = false, features = [
  "unstable",
] }
embassy-futures = "0.1.2"
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-graphics-core = { version = "0.4.0" }
embedded-graphics = { version = "0.8.1" }
embassy-sync = "0.7.2"
heapless = { version = "0.9.2", features = ["defmt"] }
once_cell = { version = "1.21.3", default-features = false, features = [
  "critical-section",
] }
tinybmp = "0.7.0"

ssd1680-rs = { git = "https://github.com/nponsard/ssd1680-rs.git", features = [
  "async",
] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(context, values(any()))',
] }
